name: Install Xray and Run update_sub

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00（北京时间 08:00）
  workflow_dispatch:  # 手动触发
  
jobs:
  install-xray:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Xray-core
      run: |
        curl -L https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip -o xray.zip
        unzip xray.zip -d xray
        chmod +x xray/xray
        mv xray/xray /usr/local/bin/xray
        xray --version

    - name: Install Python dependencies
      run: |
        python3 -m pip install --user requests

    - name: Run update_sub.py
      run: |
        python3 update_sub.py

    - name: Commit sub.txt to repository
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add sub.txt
          git commit -m 'Update sub.txt with new proxies'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload sub.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sub-files
          path: sub.txt
