name: Install Xray in Actions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  install-xray:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Xray-core (无 root)
      run: |
        # 下载最新 Xray 预编译二进制（Linux 64 位）
        curl -L https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip -o xray.zip
        unzip xray.zip -d xray
        chmod +x xray/xray
        mv xray/xray /usr/local/bin/xray
        xray --version  # 验证安装

        # 下载 geodata（可选）
        curl -L https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat -o geoip.dat
        curl -L https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat -o geosite.dat

    - name: Run update_sub.py
      run: |
        # 确保 Python 环境
        python3 -m pip install requests
        # 运行你的脚本
        python3 update_sub.py
